import { Question, Category, AIModel } from "@shared/schema";
import { 
  Atom, History, Calculator, Globe, Dna, BookOpen, Lightbulb, Languages, Microscope,
  Briefcase, Scale, Stethoscope, Brain, Laptop, Telescope, Cog, Users, Book
} from "lucide-react";

export const categories: Category[] = [
  {
    id: "physics",
    name: "Physics",
    icon: "Atom",
    description: "Test your understanding of classical and modern physics concepts",
    questionCount: 25,
    difficulty: "Hard",
  },
  {
    id: "history",
    name: "History",
    icon: "History",
    description: "Explore world history from ancient civilizations to modern times",
    questionCount: 30,
    difficulty: "Medium",
  },
  {
    id: "mathematics",
    name: "Mathematics",
    icon: "Calculator",
    description: "Challenge yourself with algebra, geometry, and calculus problems",
    questionCount: 20,
    difficulty: "Hard",
  },
  {
    id: "geography",
    name: "Geography",
    icon: "Globe",
    description: "Discover facts about countries, capitals, and natural features",
    questionCount: 28,
    difficulty: "Easy",
  },
  {
    id: "biology",
    name: "Biology",
    icon: "Dna",
    description: "Understand living organisms and life processes",
    questionCount: 22,
    difficulty: "Medium",
  },
  {
    id: "literature",
    name: "Literature",
    icon: "BookOpen",
    description: "Explore classic and contemporary works of literature",
    questionCount: 24,
    difficulty: "Medium",
  },
  {
    id: "philosophy",
    name: "Philosophy",
    icon: "Lightbulb",
    description: "Delve into ethical theories and philosophical thought",
    questionCount: 18,
    difficulty: "Hard",
  },
  {
    id: "language",
    name: "Language",
    icon: "Languages",
    description: "Test your linguistics and language comprehension skills",
    questionCount: 26,
    difficulty: "Easy",
  },
  {
    id: "chemistry",
    name: "Chemistry",
    icon: "Microscope",
    description: "Master chemical reactions, elements, and compounds",
    questionCount: 21,
    difficulty: "Hard",
  },
];

export const categoryIcons = {
  Atom,
  History,
  Calculator,
  Globe,
  Dna,
  BookOpen,
  Lightbulb,
  Languages,
  Microscope,
  Briefcase,
  Scale,
  Stethoscope,
  Brain,
  Laptop,
  Telescope,
  Cog,
  Users,
  Book,
};

export const sampleQuestions: Question[] = [
  {
    id: "1",
    subject: "Physics",
    difficulty: "Hard",
    question: "What is the speed of light in a vacuum?",
    options: [
      "299,792,458 meters per second",
      "300,000,000 meters per second",
      "186,282 miles per second",
      "299,792 kilometers per second",
    ],
    correctAnswer: 0,
    explanation: "The speed of light in a vacuum is exactly 299,792,458 meters per second, a fundamental constant in physics denoted by 'c'.",
  },
  {
    id: "2",
    subject: "History",
    difficulty: "Medium",
    question: "In which year did World War II end?",
    options: ["1943", "1944", "1945", "1946"],
    correctAnswer: 2,
    explanation: "World War II ended in 1945, with Germany surrendering in May and Japan in September after the atomic bombings.",
  },
  {
    id: "3",
    subject: "Mathematics",
    difficulty: "Hard",
    question: "What is the derivative of sin(x)?",
    options: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"],
    correctAnswer: 0,
    explanation: "The derivative of sin(x) with respect to x is cos(x), a fundamental result in calculus.",
  },
  {
    id: "4",
    subject: "Biology",
    difficulty: "Medium",
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"],
    correctAnswer: 2,
    explanation: "Mitochondria are known as the powerhouse of the cell because they generate most of the cell's ATP through cellular respiration.",
  },
  {
    id: "5",
    subject: "Geography",
    difficulty: "Easy",
    question: "What is the capital of France?",
    options: ["London", "Berlin", "Paris", "Madrid"],
    correctAnswer: 2,
    explanation: "Paris is the capital and most populous city of France, known for landmarks like the Eiffel Tower.",
  },
  {
    id: "6",
    subject: "Literature",
    difficulty: "Medium",
    question: "Who wrote 'To Kill a Mockingbird'?",
    options: ["Harper Lee", "Mark Twain", "Ernest Hemingway", "F. Scott Fitzgerald"],
    correctAnswer: 0,
    explanation: "Harper Lee wrote 'To Kill a Mockingbird', published in 1960, which won the Pulitzer Prize.",
  },
  {
    id: "7",
    subject: "Chemistry",
    difficulty: "Hard",
    question: "What is the atomic number of Carbon?",
    options: ["4", "6", "8", "12"],
    correctAnswer: 1,
    explanation: "Carbon has an atomic number of 6, meaning it has 6 protons in its nucleus.",
  },
  {
    id: "8",
    subject: "Philosophy",
    difficulty: "Hard",
    question: "Who is considered the father of Western philosophy?",
    options: ["Plato", "Aristotle", "Socrates", "Descartes"],
    correctAnswer: 2,
    explanation: "Socrates is considered the father of Western philosophy for his contributions to ethics and epistemology.",
  },
  {
    id: "9",
    subject: "Physics",
    difficulty: "Medium",
    question: "What is Newton's first law of motion?",
    options: [
      "F = ma",
      "An object at rest stays at rest unless acted upon by force",
      "For every action there is an equal and opposite reaction",
      "E = mc²",
    ],
    correctAnswer: 1,
    explanation: "Newton's first law states that an object will remain at rest or in uniform motion unless acted upon by an external force.",
  },
  {
    id: "10",
    subject: "History",
    difficulty: "Easy",
    question: "Who was the first President of the United States?",
    options: ["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"],
    correctAnswer: 1,
    explanation: "George Washington served as the first President of the United States from 1789 to 1797.",
  },
];

export const aiModels: AIModel[] = [
  { name: "GPT-4", accuracy: 86, color: "hsl(var(--chart-1))" },
  { name: "Claude 3.5 Sonnet", accuracy: 82, color: "hsl(var(--chart-2))" },
  { name: "Gemini Ultra", accuracy: 79, color: "hsl(var(--chart-3))" },
  { name: "GPT-3.5", accuracy: 72, color: "hsl(var(--chart-4))" },
  { name: "Claude 3 Opus", accuracy: 78, color: "hsl(var(--chart-5))" },
];
